### ISSUE TITLE
Most new EU units GIFs are bad looking

### ISSUE THREAD

**Issue by matxx** [BluuArc/BFFrameAnimator#3]
So here is what happens with a lot of new units (Nimnah, Charlotte, KOF units, Sergyo, Julia...)

When you do not use opacity, there's a big bubble behind units (red for fire units, blue for water...)
![unit_710197_1idle_nopac](https://cloud.githubusercontent.com/assets/990728/23773131/27f527a0-051e-11e7-920d-b8ca3a389917.gif)

But when you're using opacity, it is not good either: the bubble is less obvious to see, but it is still here, blinking / resizing behind the unit 
![unit_710197_1idle_opac](https://cloud.githubusercontent.com/assets/990728/23773126/2598749e-051e-11e7-99f7-045ffddbddf5.gif)

![unit_720197_1idle_opac](https://cloud.githubusercontent.com/assets/990728/23773220/8e3c0fa6-051e-11e7-9543-1a602f4d0178.gif)

![unit_740226_1idle_opac](https://cloud.githubusercontent.com/assets/990728/23773236/9f76598e-051e-11e7-98e5-b243f3942434.gif)

in game its like a little bubble with blur effect (not blinking, always same size)

**Comment by BluuArc** [comment]
I think that's due to how transparency doesn't translate well into GIFs. For example, in the animation strips for Mai, the bubble/transparent effects are present.

![unit_idle_710196_opac](https://cloud.githubusercontent.com/assets/16447522/23780195/056db5ac-050b-11e7-9e6a-ce91e2a16d99.png)

![unit_move_710196_opac](https://cloud.githubusercontent.com/assets/16447522/23780190/f91ef676-050a-11e7-8b1c-dccbab45a41e.png)

But, as seen in your example and as I have regenerated below, the first directly from the sprite sheet and the second from the idle strip above, that circle isn't present. This is possibly due to the bubble and similar mostly transparent effects being too transparent to be picked up when converted to GIF form.

![unit_710196_1idle_opac_shrink](https://cloud.githubusercontent.com/assets/16447522/23780239/5d30d3dc-050b-11e7-9145-f3e4ce7025e6.gif)

![unit_710196_1idle_opac_strip_shrink](https://cloud.githubusercontent.com/assets/16447522/23780262/6b030dfe-050b-11e7-8f42-8105c6d24e6a.gif)


I could try tweaking the opacity values a bit to make the bubbles show up more, but it would possibly make other units' effects blotchy as a result (i.e. only parts of effects would show up as blurry messes in some frames). Alternatively, we could try generating with a colored background to fix the transparency issues, but that would remove the opacity aspect of the animation.

**Comment by matxx** [comment]
Maybe you could add an option to disable the bubbles, I have no idea if it's something easily distinguishable

**Comment by BluuArc** [comment]
There isn't a way to easily distinguish those, as far as I know.
